apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:auWqZLHgTZc=,iv:PAfcFrgYRJjTvvh5aMoy1MmE3zdSjZiK4P3jZpzfFGc=,tag:ZpjZv1UrpFfAw6elAnZSwQ==,type:str]
sops:
  age:
    - recipient: age1va0ghtxyj42dgfw5fla5u0n7lhmxh5emv57h4yc7fq4zmg7hnv9qqm42ap
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJekM5N2oxQmVKcDFuMU9l
        cU9SdHQwRVRNclJiWWhQRWl6V1hXVTRGaFVFCnZlNWZRbzdyejJqTUNnb3c0dEZu
        MXBKT3RPTllDODZubVhjYnV2NWdYUzAKLS0tIDNnak9MbWxtelpVTmJMSTkzMHU4
        elZlSGxOblE1Vkg3Z0dlRE1ld1ZSODgK0iqz5BmBowdCwKH90jN2doBpCF1IGdSN
        x5+4qrlipAyuwGOC2MGLKgQcvQOxtom/PDWrSRsCJYllB4TpsYlKLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T20:29:53Z"
  mac: ENC[AES256_GCM,data:w5oE40i91g4Q5JQZpl9Z5hlighW6jlKC3hiJv502xVXf8cIyp+qrrZZ5QWHhi5kryB9BhoSKV+EdkASxCIHkiE8RI/UHrVXf2V/T8y1PRLABxmQ6YJUiGD2uhDGAh2Qn71cElhGb/zC3PyZVR9QdR5HDc/C2UQlUaWqlbkSrcCQ=,iv:LK69ID4dQXmzax/My+aq1aFy4ocJWfbxIrS3C65yKlI=,tag:Ybxyhb0Ft/sl3JfVqinhDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
