apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:BO0B7b8uB10sr0GE2nHnvSMF3lohRTrKbKFmmLicRmLB4lWXYJy5OFLPvmSgtGA/wmFvGRTHnytYmepGdeaGuw==,iv:WQiUwZMl9LehUZav30q6Kvujna1VY+jU1EArK/jZ3ik=,tag:J3QJwefEmB/Dt9N95jidRw==,type:str]
sops:
  age:
    - recipient: age1va0ghtxyj42dgfw5fla5u0n7lhmxh5emv57h4yc7fq4zmg7hnv9qqm42ap
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UCs5ejlMODZQSWkrbmhG
        dVk0WUl5V29SWVhMV1dHakdXejIycFZ4OURJCmZSakFpVEhEc0VJS055ZzNzbDlT
        NDBSNUJyREdhbXhzNXBZL2hQZFFscGsKLS0tIFJYcHNkVjA4cnhRd05QZlpYVE8v
        S3hoR2dGVlpTYzJSN2t6REJ0STQ1MVUKxmZdvBf08CrccEC8mpOO0qZAoXIOIjSh
        l6jLu1B76J6wdhSClfuGHmOcf6eAcdWKuYCfy9RIP0cbyfPEBFg33g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T10:50:39Z"
  mac: ENC[AES256_GCM,data:xOx7eIk3YozW9tS89wuTbfS27OeRrVOQ9mokxLH6KiZ6DSpNzGfUF99SuH83G6tUYXxXyM1c01SGOkqT8tQZKgB7M1AZAi10AIG6rTQ43JfBCPw+BTtAwW26Z3IyW+ANGv7280PNvW+lY06xTf1P291b33BZDvFojgqvxLKAXnQ=,iv:UuiXaG3pqA7RpkbUJGEYPXt8dEv/HsAzcre5rQ+ccmI=,tag:y9uyo44jd39z8stkSaBLZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
