apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:XP4URYcNtswh+dJxJ7nfZh2sa/KtneWvQljZI1RIWnHJi0XYcmmIAA37a6nPqbqkmCnuJtk=,iv:LCTlrYnfqkAUqENvIj6l39DwnSktyc5TgtbmtxPdNYA=,tag:OkHct3raxZ7UQbq0PqPWMg==,type:str]
sops:
  age:
    - recipient: age1va0ghtxyj42dgfw5fla5u0n7lhmxh5emv57h4yc7fq4zmg7hnv9qqm42ap
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q3ZkT21NVldFYlIwUWgr
        eVd4c2VWNXc5MFc1ZWRsd2UydTRtZlBKZTMwCkdiNER2WWlDWWswVFY1ZXpMNDhp
        SzBRbFFFVHB1QUxVbWJuOWxta05ycDgKLS0tIE1paE8rVGVTcVZURE1VaC9GMkdz
        ait2NWpXNkxBL0dzU1YrQ2R3ZXlxUXcK5u79bFKOZFd+4g8SJVOW/Q/2pZB0oQWB
        lEA1fswkeLy0nMk9GfSlAOtV0ifACNo1rXway6iTxMLLGH6CO2P/nQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T20:43:39Z"
  mac: ENC[AES256_GCM,data:I4e9O1AkaBS4bqQT/iotdOv8J1N1Z2DFwl2gYGZJMbjrDAVByDzpph6lQvoOqFPJsXBoAlRHtTBtdycJF6F7XbhQUGaa/iBLPU+yyUf/llhmZtpGt1WotIzmxOoRtK4uyWaqswU/HMFG4Kt2iuG806eFdtISeIq5eTtma6F0rkI=,iv:Zfn1ZzAUbHuTfRfI18xSy2cPuJp25lf0hjIkqGqFc20=,tag:bCcJcPhfkO66IY+uwJEeiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
