apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: network
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:GBo+dDwzmtNqsfpKSNkiXVo=,iv:1ik5Q7o0JMrvknxCirOS+e3f07PhFqqcJFnjtfBT580=,tag:uJIQt2nchhxG9RaHIZGKgA==,type:str]
  client_secret: ENC[AES256_GCM,data:5LwjaiQDGTPWm9bvjP1hbzjXye2uaOFCQ7tFg9sakfKfDEzg1nSe8jFwJ3zaCkLei81YVPXRotHz7BudNMuV,iv:EXnZ6NTKrDbjUluFJkTRUR6BuX6d7eSVE85MTJDFiB0=,tag:7wPm41lQHcigGtH2gIxiOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRnJ4RmJkb2E4VTBUKzJP
        aCtpOXFTcFA1ZXNsbi9WRFdSOWJ0Q0JDeHo0CjlvK2JaNk5PMU9pRm1ZUThtbjVV
        d08rL2Jkcm82ZDFRVzgwcFVUYUF0ZE0KLS0tIEdkQll3bStxcVF3VXkzQWNwMFB0
        dFZZYjlWSDVlVUpJQ1pLMCs5OWVES3cKumoY8sPd18D68M/6LXueahsPbUzPXBrN
        3GXDRrGs89CSWG4sgvR0xcLLlytILw2rLGAjUbdUsS1awCGOT5nmtg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1va0ghtxyj42dgfw5fla5u0n7lhmxh5emv57h4yc7fq4zmg7hnv9qqm42ap
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T20:23:03Z"
  mac: ENC[AES256_GCM,data:HUUT3NWT0xQNeeRXVe/RfYvfGesJHwRlbu6x84PbRX7i2FwEL9yZnkEMNymXKX3b7nYPoanOCCgM38HG6Pj4ZzoUnXTFkqCshk8c4Oie4L6mVf6JA9iB+kyVHJWk8pJ10s2GsWvCvh7fT8sDixUrL28oVQQ66y6W+nrJ9FW9uaQ=,iv:wpzo4pGkWTz076BSNHgVrW9cJTSX80HzawXCh6gYFj0=,tag:4I4voNQPxJ72zLoNdfum8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
