apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
  ports:
    - 10250
  protocol: tcp
ingress:
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
  - subnet: 100.64.0.0/10
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: talos-apid-ingress
portSelector:
  ports:
    - 50000
  protocol: tcp
ingress:
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
  - subnet: 100.64.0.0/10
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: talos-trustd-ingress
portSelector:
  ports:
    - 50001
  protocol: tcp
ingress:
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: cilium-wireguard
portSelector:
  ports:
    - 51871
  protocol: udp
ingress:
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: cilium-vxlan
portSelector:
  ports:
    - 8472
  protocol: udp
ingress:
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: cilium-health
portSelector:
  ports:
    - 4240
  protocol: tcp
ingress:
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: spegel-registry-ingress
portSelector:
  ports:
    - 5000
  protocol: tcp
ingress:
  - subnet: 10.42.0.0/16
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
  - subnet: 100.64.0.0/10
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: spegel-router-tcp-ingress
portSelector:
  ports:
    - 5001
  protocol: tcp
ingress:
  - subnet: 10.42.0.0/16
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
  - subnet: 100.64.0.0/10
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: spegel-router-udp-ingress
portSelector:
  ports:
    - 5001
  protocol: udp
ingress:
  - subnet: 10.42.0.0/16
  - subnet: 45.145.226.113/32
  - subnet: 45.145.226.120/32
  - subnet: 45.145.226.222/32
  - subnet: 100.64.0.0/10
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: http-ingress
portSelector:
  ports:
    - 80
    - 443
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0